name: Run Code Submissions

on:
  push:
    paths:
<<<<<<< HEAD
      - "main/*.java"
      - "main/*.c"
      - "main/*.cpp"
      - "main/*.py"
=======
      - "/*.java"
      - "/*.c"
      - "/*.cpp"
      - "/*.py"
>>>>>>> c867e975b737a9171c6698e4b6a5cbbe6875b109

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

<<<<<<< HEAD
      - name: Detect Language
        id: detect-language
        run: |
          FILE=$(find main -type f \( -name "*.java" -o -name "*.c" -o -name "*.cpp" -o -name "*.py" \) | head -n 1)
          if [ -z "$FILE" ]; then
            echo "No source file found in main/ directory!"
            exit 1
          fi

          echo "Detected file: $FILE"
          if [[ $FILE == main/*.java ]]; then
            echo "LANGUAGE=java" >> $GITHUB_ENV
          elif [[ $FILE == main/*.c ]]; then
            echo "LANGUAGE=c" >> $GITHUB_ENV
          elif [[ $FILE == main/*.cpp ]]; then
            echo "LANGUAGE=cpp" >> $GITHUB_ENV
          elif [[ $FILE == main/*.py ]]; then
            echo "LANGUAGE=python" >> $GITHUB_ENV
          else
            echo "No valid file detected!"
            exit 1
          fi

      - name: Run Tests
        run: |
          case $LANGUAGE in
            java)
              mkdir -p out
              javac -d out main/Main.java testcases/MainTest.java
              java -cp out testcases.MainTest
              ;;
            c)
              if [ -f testcases/ctest.c ]; then
                gcc main/main.c testcases/ctest.c -o ctest
                ./ctest
              else
                echo "C test file not found!"
                exit 1
              fi
              ;;
            cpp)
              if [ -f testcases/cpptest.cpp ]; then
                g++ main/main.cpp testcases/cpptest.cpp -o cpptest
                ./cpptest
              else
                echo "C++ test file not found!"
                exit 1
              fi
              ;;
            python)
              if [ -f testcases/pythontest.py ]; then
                python3 testcases/pythontest.py
              else
                echo "Python test file not found!"
=======
      - name: Set file and language
        id: detect-language
        run: |
          FILE=$(find . -type f \( -name ".java" -o -name ".c" -o -name ".cpp" -o -name ".py" \) | head -n 1)
          echo "Detected file: $FILE"
          if [[ $FILE == *.java ]]; then
            echo "TEST_FILE=testcases/javatest.java" >> $GITHUB_ENV
          elif [[ $FILE == *.c ]]; then
            echo "TEST_FILE=testcases/ctest.c" >> $GITHUB_ENV
          elif [[ $FILE == *.cpp ]]; then
            echo "TEST_FILE=testcases/cpptest.cpp" >> $GITHUB_ENV
          elif [[ $FILE == *.py ]]; then
            echo "TEST_FILE=testcases/pythontest.python" >> $GITHUB_ENV
          else
            echo "No valid file detected!"
            exit 1
          fi

      - name: Run respective test cases
        run: |
          case $TEST_FILE in
            testcases/javatest.java)
              javac $TEST_FILE
              if [ $? -eq 0 ]; then
                java ${TEST_FILE%.java}
              else
                echo "Java test failed!"
                exit 1
              fi
              ;;
            testcases/ctest.c)
              gcc $TEST_FILE -o ctest
              if [ $? -eq 0 ]; then
                ./ctest
              else
                echo "C test failed!"
                exit 1
              fi
              ;;
            testcases/cpptest.cpp)
              g++ $TEST_FILE -o cpptest
              if [ $? -eq 0 ]; then
                ./cpptest
              else
                echo "C++ test failed!"
                exit 1
              fi
              ;;
            python -m testcases.pythontest)
              python3 $TEST_FILE
              if [ $? -ne 0 ]; then
                echo "Python test failed!"
>>>>>>> c867e975b737a9171c6698e4b6a5cbbe6875b109
                exit 1
              fi
              ;;
            *)
              echo "No valid test file found!"
              exit 1
              ;;
          esac
